apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-kpack-testing
spec:
  title: Kpack Testing
  description: Play area for testing kpack
  content:
    files: github.com/eduk8s-tests/lab-kpack-testing
  session:
    objects:
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: Role
        metadata:
          name: kontinue-access
        rules:
          - apiGroups:
              - experimental.kontinue.io
              - kpack.io
              - serving.knative.dev
              - source.toolkit.fluxcd.io
              - opinions.local
            resources: ['*']
            verbs: ['*']
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: kontinue-access
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: Role
          name: kontinue-access
        subjects:
          - kind: ServiceAccount
            namespace: $(workshop_namespace)
            name: $(service_account)
